@startjson Resposta em Json
{
    "errors": [
        {
            "line": 1,
            "message": "Error in line 1."
        },
        {
            "line": 2,
            "message": "Error in line 2."
        },
        {
            "line": 3,
            "message": "Error in line 3."
        }
       
    ]
}
@endjson

